default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: ryuya
  password: arorida45
  pool: 5

development:
  <<: *default
  database: development
  password: password


test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  database: test

production:
  <<: *default
  database: myapp_production
  username: ryuya
  host: <%= ENV["DB_HOST"] %>
  password: <%= ENV["DB_PASSWORD"] %>
