name: push image to ECR and deploy to ECS
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  push:
    name: push image to ECR and deploy to ECS
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      # - name: Set AWS CLI Debug Output (if needed for debugging)
      #   run: |
      #     echo "AWS_DEFAULT_OUTPUT=text" >> $GITHUB_ENV
      #     echo "AWS_PAGER=" >> $GITHUB_ENV
      #     # echo "AWS_DEBUG=true" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1' #変更してください リージョン名
          role-to-assume: 'arn:aws:iam::756082435632:role/github-actions-ecr-push-role' #変更してください ロール名

      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Build, tag, and push docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "project-a" #変更してください ECRのリポジトリ名
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Force new deployment and wait for services stability in ECS
        env:
          CLUSTER_NAME: "ProjectB-ecs-cluster" #変更してください クラスター名
          SERVICE_NAME: "ProjectB-ecs-service3" #変更してください サービス名
        run: |
          aws ecs update-service --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME }} --force-new-deployment
          aws ecs wait services-stable --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME }}
          aws ecs describe-services --cluster ${{ env.CLUSTER_NAME }} --service ${{ env.SERVICE_NAME }}

# test9
